#+TITLE: The Divine Liturgy of Saint John Chrysostom

(For use at Holy Trinity Greek Orthodox parish, Fort Wayne, Indiana.)

THE DIVINE LITURGY OF ST. JOHN CHRYSOSTOM

PRIEST

Blessed is the Kingdom of the Father and of the Son and of the Holy Spirit, now and forever and to the ages of ages.

(Amen.)

* THE LITANY OF PEACE

DEACON

In peace, let us pray to the Lord.

(Lord, have mercy.)

For the peace from above and for the salvation of our souls, let us pray to the Lord.

(Lord, have mercy.)

For the peace of the whole world, for the stability of the holy churches of God, and for the unity of all, let us pray to the Lord.

(Lord, have mercy.)

For this holy house and for those who enter it with faith, reverence, and the fear of God, let us pray to the Lord.

(Lord, have mercy.)

For pious and Orthodox Christians, let us pray to the Lord.

(Lord, have mercy.)

For (episcopal rank) (name), for the honorable presbyterate, for the diaconate in Christ, and for all the clergy and the people, let us pray to the Lord.

(Lord, have mercy.)

For our country, for the president, and for all in public service, let us pray to the Lord.

(Lord, have mercy.)

For this city, and for every city and land, and for the faithful who live in them, let us pray to the Lord.

(Lord, have mercy.)

For favorable weather, for an abundance of the fruits of the earth, and for peaceful times, let us pray to the Lord.

(Lord, have mercy.)

For those who travel by land, sea, and air, for the sick, the suffering, the captives and for their salvation, let us pray to the Lord.

(Lord, have mercy.)

For our deliverance from all affliction, wrath, danger and distress, and from the peril of the coronavirus against us, let us pray to the Lord.

(Lord, have mercy.)

Help us, save us, have mercy on us, and protect us, O God, by Your grace.

(Lord, have mercy.)

Commemorating our most holy, pure, blessed, and glorious Lady, the Theotokos and ever-virgin Mary, with all the saints, let us commend ourselves and one another and our whole life to Christ our God.

(To You, O Lord.)

PRIEST

For to You belong all glory, honor, and worship, to the Father and to the Son and to the Holy Spirit, now and forever and to the ages of ages.

(Amen.)

* FIRST ANTIPHON

(Designated Psalm verses are intoned prior to the following refrain.)

CHOIR

Through the intercessions of the Theotokos, Savior, save us.

* THE SMALL LITANY

DEACON

Again and again, in peace, let us pray to the Lord.

(Lord, have mercy.)

Help us, save us, have mercy on us, and protect us, O God, by Your grace.

(Lord, have mercy.)

Commemorating our most holy, pure, blessed, and glorious Lady, the Theotokos and ever-virgin Mary, with all the saints, let us commend ourselves and one another and our whole life to Christ our God.

(To You, O Lord.)

PRIEST

For Yours is the dominion, and Yours is the kingdom and the power and the glory, of the Father and of the Son and of the Holy Spirit, now and forever and to the ages of ages.

(Amen.)

* SECOND ANTIPHON

(Designated Psalm verses are intoned prior to the following refrain.)

CHOIR

Save us, O Son of God, risen from the dead. We sing to You, Alleluia.

Glory to the Father and the Son and the Holy Spirit. Both now and ever and to the ages of ages. Amen.

# From the old Green Book:

Only begotten Son and Word of God, Immortal One, who for our salvation did so humble Yourself by taking on flesh, taking flesh by, by the Theotokos and ever-virgin Mary; without change did You become man, and were crucified, Christ our God; but conquered death by Your death. As one of the Holy Trinity, and being glorified together with the Father and the Holy Spirit, save us.

* THE SMALL LITANY

DEACON

Again and again, in peace, let us pray to the Lord.

(Lord, have mercy.)

Help us, save us, have mercy on us, and protect us, O God, by Your grace.

(Lord, have mercy.)

Commemorating our most holy, pure, blessed, and glorious Lady, the Theotokos and ever-virgin Mary, with all the saints, let us commend ourselves and one another and our whole life to Christ our God.

(To You, O Lord.)

PRIEST

For You, O God, are good and love mankind, and to You we offer glory, to the Father and to the Son and to the Holy Spirit, now and forever, and to the ages of ages.

(Amen.) 

* Antiphon III

(While the hymn of the day is sung, the priest carrying the holy Gospel Book comes in procession before the Beautiful Gate of the Icon Screen. The priest blesses the entrance. He then raises the Holy Gospel Book and says:)

